//! `SeaORM` Entity. Generated by sea-orm-codegen 0.10.6

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "role")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: u64,
    pub guild: u64,
    pub whitelisted: bool,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::guild_data::Entity",
        from = "Column::Guild",
        to = "super::guild_data::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    GuildData,
}

impl Related<super::guild_data::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::GuildData.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
