//! `SeaORM` Entity. Generated by sea-orm-codegen 0.10.6

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "sticker_pack")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: u64,
    pub prefix: String,
    pub display_name: Option<String>,
    pub creator: Option<i32>,
    pub creation_date: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::sticker::Entity")]
    Sticker,
}

impl Related<super::sticker::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Sticker.def()
    }
}

impl Related<super::guild_data::Entity> for Entity {
    fn to() -> RelationDef {
        super::guild_pack_rel::Relation::GuildData.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::guild_pack_rel::Relation::StickerPack.def().rev())
    }
}

impl Related<super::user_data::Entity> for Entity {
    fn to() -> RelationDef {
        super::user_pack_rel::Relation::UserData.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::user_pack_rel::Relation::StickerPack.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}
