//! `SeaORM` Entity. Generated by sea-orm-codegen 0.10.6

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "sticker")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: u64,
    pub name: String,
    pub creator: Option<u64>,
    pub creation_date: Option<String>,
    pub guild: Option<u64>,
    pub user: Option<u64>,
    pub pack: Option<u64>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::guild_data::Entity",
        from = "Column::Guild",
        to = "super::guild_data::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    GuildData,
    #[sea_orm(
        belongs_to = "super::sticker_pack::Entity",
        from = "Column::Pack",
        to = "super::sticker_pack::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    StickerPack,
    #[sea_orm(
        belongs_to = "super::user_data::Entity",
        from = "Column::User",
        to = "super::user_data::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    UserData,
}

impl Related<super::guild_data::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::GuildData.def()
    }
}

impl Related<super::sticker_pack::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::StickerPack.def()
    }
}

impl Related<super::user_data::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UserData.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
